# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/hexospace/hexo/source/prj/prj_led/prj_led/prj_led.cache/wt [current_project]
set_property parent.project_path D:/hexospace/hexo/source/prj/prj_led/prj_led/prj_led.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/hexospace/hexo/source/prj/prj_led/prj_led/prj_led.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/hexospace/hexo/source/prj/prj_led/prj_led/prj_led.srcs/sources_1/new/led.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/hexospace/hexo/source/prj/prj_led/prj_led/my_xdc/led_pin.xdc
set_property used_in_implementation false [get_files D:/hexospace/hexo/source/prj/prj_led/prj_led/my_xdc/led_pin.xdc]


synth_design -top led -part xc7z020clg400-2


write_checkpoint -force -noxdef led.dcp

catch { report_utilization -file led_utilization_synth.rpt -pb led_utilization_synth.pb }
